[book]
authors = ["PeaceShi"]
language = "cmn-Hans"
description = "游戏编程模式"
multilingual = false
src = "src"
title = "游戏编程模式"
[build]
create-missing = true
[output.html]
theme = "src/theme"
default-theme = "rust"
additional-css = ["theme/theme.css"]
additional-js = ["plugin/mermaid.min.js", "plugin/mermaid-init.js"]
git-repository-url = "https://github.com/peaceshi/GameProgrammingPatterns"
[output.html.playpen]
editable = false
copy-js = true
line-numbers = false
[output.html.search]
enable = false
[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]
