name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Setup CDN 
        run: |
          npm install
          npm run release
          export HEAD=$(git rev-parse --short HEAD)
          sed -i 's/@master/@'$HEAD'/g' $GITHUB_WORKSPACE/src/theme/index.hbs
      - name: Setup mermaid
        run: |
          export mermaid_VERSION="0.2.2"
          export mermaid_TARBALL="mdbook-mermaid-${mermaid_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          wget -q "https://github.com/badboy/mdbook-mermaid/releases/download/${mermaid_VERSION}/${mermaid_TARBALL}"
          tar -zxvf "${mermaid_TARBALL}"
          rm "${mermaid_TARBALL}"
          mkdir -p $GITHUB_WORKSPACE/bin
          mv ./mdbook-mermaid $GITHUB_WORKSPACE/bin
          echo "::add-path::$GITHUB_WORKSPACE/bin"
          chmod +x $GITHUB_WORKSPACE/bin/mdbook-mermaid
      - name: Setup github pages
        uses: peaceiris/actions-mdbook@master
        with:
          mdbook-version: "0.3.6"
          # mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@master
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./book
